# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_camera(object):
    def setupUi(self, camera):
        camera.setObjectName("camera")
        camera.resize(1269, 892)
        self.centralwidget = QtWidgets.QWidget(camera)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 791, 611))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.DispLb = QtWidgets.QLabel(self.frame)
        self.DispLb.setGeometry(QtCore.QRect(10, 10, 771, 581))
        self.DispLb.setObjectName("DispLb")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(810, 10, 441, 611))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ShowBt = QtWidgets.QPushButton(self.frame_2)
        self.ShowBt.setGeometry(QtCore.QRect(10, 500, 91, 23))
        self.ShowBt.setObjectName("ShowBt")
        self.StopBt = QtWidgets.QPushButton(self.frame_2)
        self.StopBt.setGeometry(QtCore.QRect(120, 500, 91, 23))
        self.StopBt.setObjectName("StopBt")
        self.RedColorSpB = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.RedColorSpB.setGeometry(QtCore.QRect(320, 110, 62, 22))
        self.RedColorSpB.setDecimals(0)
        self.RedColorSpB.setMaximum(255.0)
        self.RedColorSpB.setProperty("value", 255.0)
        self.RedColorSpB.setObjectName("RedColorSpB")
        self.RedColorSld = QtWidgets.QSlider(self.frame_2)
        self.RedColorSld.setGeometry(QtCore.QRect(100, 110, 201, 22))
        self.RedColorSld.setMaximum(255)
        self.RedColorSld.setProperty("value", 255)
        self.RedColorSld.setSliderPosition(255)
        self.RedColorSld.setOrientation(QtCore.Qt.Horizontal)
        self.RedColorSld.setObjectName("RedColorSld")
        self.GreenColorSld = QtWidgets.QSlider(self.frame_2)
        self.GreenColorSld.setGeometry(QtCore.QRect(100, 150, 201, 22))
        self.GreenColorSld.setMaximum(255)
        self.GreenColorSld.setProperty("value", 255)
        self.GreenColorSld.setOrientation(QtCore.Qt.Horizontal)
        self.GreenColorSld.setObjectName("GreenColorSld")
        self.BlueColorSld = QtWidgets.QSlider(self.frame_2)
        self.BlueColorSld.setGeometry(QtCore.QRect(100, 190, 201, 22))
        self.BlueColorSld.setMaximum(255)
        self.BlueColorSld.setProperty("value", 255)
        self.BlueColorSld.setOrientation(QtCore.Qt.Horizontal)
        self.BlueColorSld.setObjectName("BlueColorSld")
        self.GreenColorSpB = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.GreenColorSpB.setGeometry(QtCore.QRect(320, 150, 62, 22))
        self.GreenColorSpB.setDecimals(0)
        self.GreenColorSpB.setMinimum(0.0)
        self.GreenColorSpB.setMaximum(255.0)
        self.GreenColorSpB.setProperty("value", 255.0)
        self.GreenColorSpB.setObjectName("GreenColorSpB")
        self.BlueColorSpB = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.BlueColorSpB.setGeometry(QtCore.QRect(320, 190, 62, 22))
        self.BlueColorSpB.setDecimals(0)
        self.BlueColorSpB.setMaximum(255.0)
        self.BlueColorSpB.setSingleStep(0.0)
        self.BlueColorSpB.setProperty("value", 255.0)
        self.BlueColorSpB.setObjectName("BlueColorSpB")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 110, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        self.label_4.setStyleSheet("font: 14pt \"Consolas\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        self.label_5.setStyleSheet("font: 14pt \"Consolas\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 190, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        self.label_6.setStyleSheet("font: 14pt \"Consolas\";")
        self.label_6.setObjectName("label_6")
        self.ExpTimeSld = QtWidgets.QSlider(self.frame_2)
        self.ExpTimeSld.setGeometry(QtCore.QRect(100, 240, 201, 22))
        self.ExpTimeSld.setMinimum(-10)
        self.ExpTimeSld.setMaximum(-2)
        self.ExpTimeSld.setOrientation(QtCore.Qt.Horizontal)
        self.ExpTimeSld.setObjectName("ExpTimeSld")
        self.GainSld = QtWidgets.QSlider(self.frame_2)
        self.GainSld.setGeometry(QtCore.QRect(100, 290, 201, 22))
        self.GainSld.setOrientation(QtCore.Qt.Horizontal)
        self.GainSld.setObjectName("GainSld")
        self.BrightSld = QtWidgets.QSlider(self.frame_2)
        self.BrightSld.setGeometry(QtCore.QRect(100, 340, 201, 22))
        self.BrightSld.setOrientation(QtCore.Qt.Horizontal)
        self.BrightSld.setObjectName("BrightSld")
        self.ContrastSld = QtWidgets.QSlider(self.frame_2)
        self.ContrastSld.setGeometry(QtCore.QRect(100, 380, 201, 22))
        self.ContrastSld.setOrientation(QtCore.Qt.Horizontal)
        self.ContrastSld.setObjectName("ContrastSld")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 240, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(30, 290, 54, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(30, 340, 54, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(20, 380, 54, 20))
        self.label_10.setObjectName("label_10")
        self.ExpTimeSpB = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.ExpTimeSpB.setGeometry(QtCore.QRect(320, 240, 62, 22))
        self.ExpTimeSpB.setDecimals(2)
        self.ExpTimeSpB.setMinimum(-10.0)
        self.ExpTimeSpB.setMaximum(-2.0)
        self.ExpTimeSpB.setObjectName("ExpTimeSpB")
        self.GainSpB = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.GainSpB.setGeometry(QtCore.QRect(320, 290, 62, 22))
        self.GainSpB.setDecimals(2)
        self.GainSpB.setMaximum(128.0)
        self.GainSpB.setObjectName("GainSpB")
        self.BrightSpB = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.BrightSpB.setGeometry(QtCore.QRect(320, 340, 62, 22))
        self.BrightSpB.setDecimals(2)
        self.BrightSpB.setMinimum(-64.0)
        self.BrightSpB.setMaximum(64.0)
        self.BrightSpB.setObjectName("BrightSpB")
        self.ContrastSpB = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.ContrastSpB.setGeometry(QtCore.QRect(320, 380, 62, 22))
        self.ContrastSpB.setDecimals(2)
        self.ContrastSpB.setMaximum(100.0)
        self.ContrastSpB.setObjectName("ContrastSpB")
        self.FilePathLE = QtWidgets.QLineEdit(self.frame_2)
        self.FilePathLE.setGeometry(QtCore.QRect(80, 430, 231, 20))
        self.FilePathLE.setObjectName("FilePathLE")
        self.FilePathBt = QtWidgets.QPushButton(self.frame_2)
        self.FilePathBt.setGeometry(QtCore.QRect(320, 430, 75, 23))
        self.FilePathBt.setObjectName("FilePathBt")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(10, 430, 51, 21))
        self.label_11.setObjectName("label_11")
        self.RecordBt = QtWidgets.QPushButton(self.frame_2)
        self.RecordBt.setGeometry(QtCore.QRect(230, 500, 91, 23))
        self.RecordBt.setObjectName("RecordBt")
        self.ExitBt = QtWidgets.QPushButton(self.frame_2)
        self.ExitBt.setGeometry(QtCore.QRect(300, 570, 131, 23))
        self.ExitBt.setObjectName("ExitBt")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(160, 40, 131, 51))
        self.label_3.setStyleSheet("font: 20pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.Picbtn = QtWidgets.QPushButton(self.frame_2)
        self.Picbtn.setGeometry(QtCore.QRect(330, 500, 91, 23))
        self.Picbtn.setObjectName("Picbtn")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 620, 1231, 231))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setGeometry(QtCore.QRect(50, 20, 661, 191))
        self.groupBox.setObjectName("groupBox")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(50, 40, 54, 12))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(33, 112, 71, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(130, 40, 54, 12))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(120, 110, 171, 41))
        self.label_15.setStyleSheet("font: 75 22pt \"Agcy FB\";")
        self.label_15.setObjectName("label_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setGeometry(QtCore.QRect(730, 20, 481, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.MsgTE = QtWidgets.QTextEdit(self.groupBox_2)
        self.MsgTE.setGeometry(QtCore.QRect(20, 20, 451, 61))
        self.MsgTE.setObjectName("MsgTE")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setGeometry(QtCore.QRect(730, 110, 481, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 70, 71, 20))
        self.label.setObjectName("label")
        self.FmRateLCD = QtWidgets.QLCDNumber(self.groupBox_3)
        self.FmRateLCD.setGeometry(QtCore.QRect(90, 40, 91, 61))
        self.FmRateLCD.setObjectName("FmRateLCD")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(220, 60, 71, 20))
        self.label_2.setObjectName("label_2")
        self.ImgWidthLCD = QtWidgets.QLCDNumber(self.groupBox_3)
        self.ImgWidthLCD.setGeometry(QtCore.QRect(290, 40, 91, 61))
        self.ImgWidthLCD.setObjectName("ImgWidthLCD")
        self.ImgHeightLCD = QtWidgets.QLCDNumber(self.groupBox_3)
        self.ImgHeightLCD.setGeometry(QtCore.QRect(390, 40, 91, 61))
        self.ImgHeightLCD.setObjectName("ImgHeightLCD")
        self.timeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.timeLabel.setGeometry(QtCore.QRect(200, 10, 261, 21))
        self.timeLabel.setObjectName("timeLabel")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(130, 10, 51, 21))
        self.label_17.setObjectName("label_17")
        camera.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(camera)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1269, 23))
        self.menubar.setObjectName("menubar")
        camera.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(camera)
        self.statusbar.setObjectName("statusbar")
        camera.setStatusBar(self.statusbar)

        self.retranslateUi(camera)
        QtCore.QMetaObject.connectSlotsByName(camera)

    def retranslateUi(self, camera):
        _translate = QtCore.QCoreApplication.translate
        camera.setWindowTitle(_translate("camera", "MainWindow"))
        self.DispLb.setText(_translate("camera", "                                                          摄像头区域"))
        self.ShowBt.setText(_translate("camera", "开始"))
        self.StopBt.setText(_translate("camera", "暂停"))
        self.label_4.setText(_translate("camera", "R"))
        self.label_5.setText(_translate("camera", "G"))
        self.label_6.setText(_translate("camera", "B"))
        self.label_7.setText(_translate("camera", "曝光时间："))
        self.label_8.setText(_translate("camera", "增益："))
        self.label_9.setText(_translate("camera", "亮度："))
        self.label_10.setText(_translate("camera", "对比度："))
        self.FilePathBt.setText(_translate("camera", "路径修改"))
        self.label_11.setText(_translate("camera", "保存路径："))
        self.RecordBt.setText(_translate("camera", "保存"))
        self.ExitBt.setText(_translate("camera", "退出"))
        self.label_3.setText(_translate("camera", "参数调节"))
        self.Picbtn.setText(_translate("camera", "图片模式"))
        self.groupBox.setTitle(_translate("camera", "车牌识别结果"))
        self.label_12.setText(_translate("camera", "颜色："))
        self.label_13.setText(_translate("camera", "车牌号码："))
        self.label_14.setText(_translate("camera", "LY"))
        self.label_15.setText(_translate("camera", "浙A-XXXXXXX"))
        self.groupBox_2.setTitle(_translate("camera", "信息框"))
        self.groupBox_3.setTitle(_translate("camera", "基本信息"))
        self.label.setText(_translate("camera", "当前帧数："))
        self.label_2.setText(_translate("camera", "图像尺寸："))
        self.timeLabel.setText(_translate("camera", "TextLabel"))
        self.label_17.setText(_translate("camera", "当前时间:"))

