# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(906, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/查询-default.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(230, 0, 671, 651))
        self.tableView.setObjectName("tableView")
        self.all = QtWidgets.QPushButton(self.centralwidget)
        self.all.setGeometry(QtCore.QRect(10, 610, 211, 31))
        self.all.setObjectName("all")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 221, 161))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 40, 151, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 41, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(80, 110, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 230, 221, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(80, 20, 71, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 41, 31))
        self.label_4.setObjectName("label_4")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(40, 70, 161, 31))
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 5, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 41, 31))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 21, 31))
        self.label_2.setObjectName("label_2")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(40, 130, 161, 31))
        self.dateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 5, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.search = QtWidgets.QPushButton(self.groupBox_2)
        self.search.setGeometry(QtCore.QRect(40, 190, 161, 31))
        self.search.setObjectName("search")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.search.clicked.connect(mainWindow.GetsearchContent)
        self.all.clicked.connect(mainWindow.Getall)
        self.pushButton.clicked.connect(mainWindow.GetCarNum)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "车牌查询"))
        self.all.setText(_translate("mainWindow", "查询所有车牌"))
        self.groupBox.setTitle(_translate("mainWindow", "车牌号码查询"))
        self.label.setText(_translate("mainWindow", "车牌："))
        self.pushButton.setText(_translate("mainWindow", "车牌查询"))
        self.groupBox_2.setTitle(_translate("mainWindow", "按条件查询"))
        self.comboBox.setItemText(0, _translate("mainWindow", "全部"))
        self.comboBox.setItemText(1, _translate("mainWindow", "绿色"))
        self.comboBox.setItemText(2, _translate("mainWindow", "黄色"))
        self.comboBox.setItemText(3, _translate("mainWindow", "蓝色"))
        self.label_4.setText(_translate("mainWindow", "颜色："))
        self.dateTimeEdit.setDisplayFormat(_translate("mainWindow", "yyyy/MM/dd HH:mm:ss"))
        self.label_3.setText(_translate("mainWindow", "时间："))
        self.label_2.setText(_translate("mainWindow", "至"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("mainWindow", "yyyy/MM/dd HH:mm:ss"))
        self.search.setText(_translate("mainWindow", " 条件查询"))

